package org.academy.internal.common.ability.program;

import java.util.Locale;

public enum ProgramVmDiagnostic {
    NONE,
    MISSING_EXECUTOR,
    MISSING_INPUT_VALUE,
    INVALID_OUTPUT,
    INVALID_FLOW_OUTPUT,
    EXECUTOR_ERROR,
    ACTION_REJECTED,
    TARGET_OUT_OF_RANGE,
    INSUFFICIENT_CP,
    SKILL_UNAVAILABLE,
    TARGET_INVALID,
    TARGET_MOVEMENT_PROTECTED,
    TARGET_PROTECTED,
    TARGET_REJECTED,
    TARGET_TYPE_UNSUPPORTED,
    WORLD_UNAVAILABLE,
    BLOCK_BREAK_DISABLED,
    BLOCK_UNBREAKABLE,
    DESTINATION_BLOCKED,
    DESTINATION_UNSAFE,
    INVENTORY_FULL,
    INVALID_DIRECTION,
    POWER_LIMIT,
    SPAWN_FAILED,
    ACTION_CONDITION_FAILED,
    DIVISION_BY_ZERO,
    NON_FINITE_RESULT,
    ALREADY_RUNNING,
    EXECUTION_EXPIRED,
    CONTROL_RESISTANCE,
    NO_SIGHT_TARGET,
    NO_EFFECTIVE_SUBJECTS,
    UNREACHABLE_DESTINATION,
    PROFICIENCY_REQUIRED,
    TARGET_LIMIT,
    CLIENT_TIMEOUT,
    PLANNING_BUDGET_EXHAUSTED,
    UNSUPPORTED_MOVEMENT_MODE;

    public String translationKey() {
        var prefix = switch (this) {
            case CONTROL_RESISTANCE, NO_SIGHT_TARGET, NO_EFFECTIVE_SUBJECTS,
                 UNREACHABLE_DESTINATION, PROFICIENCY_REQUIRED, TARGET_LIMIT, CLIENT_TIMEOUT,
                 PLANNING_BUDGET_EXHAUSTED, UNSUPPORTED_MOVEMENT_MODE -> "message.academy.precision_operation.";
            default -> "message.academy.program.execution.diagnostic.";
        };
        return prefix + name().toLowerCase(Locale.ROOT);
    }
}
