/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_academy_api_client_jni_AudioDecoderJNI */

#ifndef _Included_org_academy_api_client_jni_AudioDecoderJNI
#define _Included_org_academy_api_client_jni_AudioDecoderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_init_memory
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1init_1memory
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_read_pcm_frames
 * Signature: (JLjava/nio/ByteBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1read_1pcm_1frames
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_uninit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1uninit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_get_channels
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1get_1channels
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_get_sample_rate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1get_1sample_1rate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_get_length_in_pcm_frames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1get_1length_1in_1pcm_1frames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_academy_api_client_jni_AudioDecoderJNI
 * Method:    decoder_seek_to_pcm_frame
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_academy_api_client_jni_AudioDecoderJNI_decoder_1seek_1to_1pcm_1frame
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
