package org.academy.api.common.ability.program;

public enum ProgramDiagnosticCode {
    EMPTY_PROGRAM,
    TOO_MANY_NODES,
    TOO_MANY_EDGES,
    INVALID_NODE,
    DUPLICATE_NODE,
    UNKNOWN_NODE_TYPE,
    UNSUPPORTED_NODE_SCHEMA,
    INVALID_CONFIGURATION,
    CATEGORY_MISMATCH,
    CAPABILITY_MISSING,
    DUPLICATE_EDGE,
    INVALID_EDGE,
    UNKNOWN_PORT,
    TYPE_MISMATCH,
    TOO_MANY_CONNECTIONS,
    AMBIGUOUS_FLOW,
    MISSING_INPUT,
    NO_ENTRY,
    MULTIPLE_ENTRIES,
    INVALID_ENTRY,
    UNREACHABLE_FLOW_NODE,
    DATA_CYCLE
}
