name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'zulu'

      - name: Build with Gradle
        run: .\gradlew.bat build

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: AcademyCraft
          path: build/libs/*.jar