name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Cache JBR
        id: cache-jbr
        uses: actions/cache@v4
        with:
          path: ./jbrsdk.tar.gz
          key: jbr-sdk-25-b176.4

      - name: Download JBR
        if: steps.cache-jbr.outputs.cache-hit != 'true'
        run: |
          wget -O jbrsdk.tar.gz "https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-25-linux-x64-b176.4.tar.gz"

      - name: Install JBR
        uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ./jbrsdk.tar.gz
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Dev and Release
        run: |
          ./gradlew build -DisDev=true
          ./gradlew build -DisDev=false

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: AcademyCraft
          path: 'build/libs/*.jar'