package org.academy.internal.client.gui.screen;

import net.minecraft.resources.Identifier;
import net.neoforged.fml.loading.FMLPaths;
import org.academy.AcademyCraft;
import org.academy.api.client.ability.AbilitySystemClient;
import org.academy.api.common.ability.AbilityCategory;
import org.academy.api.common.registries.Registries;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.*;

/**
 * Session-local editor state for the ability developer skill tree. The built-in resource is
 * deliberately read-only; edited coordinates are written only when the export command is used.
 */
public final class AbilityDeveloperLayoutEditor {
    private static final String RESOURCE_PATH = "/assets/academy/gui/ability_developer_gui_layout.txt";
    private static final Path EXPORT_PATH = FMLPaths.CONFIGDIR.get()
            .resolve("academy")
            .resolve("ability_developer_gui_layout.txt");
    private static final Map<String, Map<String, Position>> DEFAULT_LAYOUT = loadDefaultLayout();
    private static final Map<String, Map<String, Position>> SESSION_LAYOUT = new HashMap<>();

    private static boolean debugMode;

    private AbilityDeveloperLayoutEditor() {
    }

    public static boolean isDebugMode() {
        return debugMode;
    }

    public static boolean setDebugMode(boolean enabled) {
        debugMode = enabled;
        return debugMode;
    }

    public static boolean toggleDebugMode() {
        return setDebugMode(!debugMode);
    }

    public static Position getPosition(AbilityCategory category, AbilitySystemClient.SkillInfo info) {
        var categoryKey = category.getKey().toString();
        var skillKey = info.skill().getKeyString();
        var session = SESSION_LAYOUT.get(categoryKey);
        if (session != null && session.containsKey(skillKey)) {
            return session.get(skillKey);
        }
        var defaults = DEFAULT_LAYOUT.get(categoryKey);
        if (defaults != null && defaults.containsKey(skillKey)) {
            return defaults.get(skillKey);
        }
        return new Position(info.x(), info.y());
    }

    public static void setPosition(AbilityCategory category, AbilitySystemClient.SkillInfo info, float x, float y) {
        SESSION_LAYOUT.computeIfAbsent(category.getKey().toString(), ignored -> new HashMap<>())
                .put(info.skill().getKeyString(), new Position(snap(x), snap(y)));
    }

    public static void resetSession() {
        SESSION_LAYOUT.clear();
    }

    public static float snap(float value) {
        return Math.round(value * 2.0f) / 2.0f;
    }

    public static Path exportAll() throws IOException {
        Files.createDirectories(EXPORT_PATH.getParent());
        var categories = new ArrayList<AbilityCategory>();
        Registries.ABILITY_CATEGORIES.forEach(categories::add);
        categories.sort(Comparator.comparing(category -> category.getKey().toString()));

        var output = new StringBuilder();
        output.append("# AcademyCraft ability developer skill layout\n");
        output.append("# Generated by /academy debug skillgui export\n");
        output.append("# Coordinates are panel-local pixels and use 0.5 pixel snapping.\n\n");

        for (var category : categories) {
            output.append('[').append(category.getKey()).append("]\n");
            var infos = new ArrayList<>(AbilitySystemClient.getSkillInfosForCategory(category));
            infos.sort(Comparator.comparing(info -> info.skill().getKeyString()));
            for (var info : infos) {
                var position = getPosition(category, info);
                output.append(info.skill().getKeyString())
                        .append('=')
                        .append(format(position.x()))
                        .append(',')
                        .append(format(position.y()))
                        .append('\n');
            }
            output.append('\n');
        }

        Files.writeString(EXPORT_PATH, output.toString(), StandardCharsets.UTF_8);
        return EXPORT_PATH;
    }

    private static String format(float value) {
        return String.format(Locale.ROOT, "%.1f", value);
    }

    private static Map<String, Map<String, Position>> loadDefaultLayout() {
        var result = new LinkedHashMap<String, Map<String, Position>>();
        try (var input = AbilityDeveloperLayoutEditor.class.getResourceAsStream(RESOURCE_PATH)) {
            if (input == null) {
                AcademyCraft.getLogger().warn("Missing built-in ability developer layout {}", RESOURCE_PATH);
                return result;
            }
            try (var reader = new BufferedReader(new InputStreamReader(input, StandardCharsets.UTF_8))) {
                String category = null;
                String line;
                while ((line = reader.readLine()) != null) {
                    line = line.strip();
                    if (line.isEmpty() || line.startsWith("#")) continue;
                    if (line.startsWith("[") && line.endsWith("]")) {
                        var raw = line.substring(1, line.length() - 1).strip();
                        category = Identifier.parse(raw).toString();
                        result.computeIfAbsent(category, ignored -> new LinkedHashMap<>());
                        continue;
                    }
                    if (category == null) continue;
                    var equals = line.indexOf('=');
                    var comma = line.indexOf(',', equals + 1);
                    if (equals <= 0 || comma <= equals) continue;
                    var skill = Identifier.parse(line.substring(0, equals).strip()).toString();
                    var x = Float.parseFloat(line.substring(equals + 1, comma).strip());
                    var y = Float.parseFloat(line.substring(comma + 1).strip());
                    if (Float.isFinite(x) && Float.isFinite(y)) {
                        result.get(category).put(skill, new Position(snap(x), snap(y)));
                    }
                }
            }
        } catch (RuntimeException | IOException exception) {
            AcademyCraft.getLogger().error("Unable to load built-in ability developer layout", exception);
        }
        return result;
    }

    public record Position(float x, float y) {
    }
}
